services:
  web:
    image: dicapi-backend:latest
    command: npm run dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - swarm_net
    ports:
      - "8080:8080"
    environment:
      - MEMCACHED_URL=cache:11211
      - DB_HOST=db
    deploy:
      placement:
        constraints:
          - node.labels.is-web == true
    restart: always
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: dic_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scheme.sql:/docker-entrypoint-initdb.d/scheme.sql
    networks:
      - swarm_net
    deploy:
      placement:
        constraints:
          - node.labels.is-db == true
  cache:
    image: memcached:alpine
    networks:
      - swarm_net
    deploy:
      endpoint_mode: dnsrr
      replicas: 3
      placement:
        constraints:
          - node.labels.is-cache == true
    restart: always

volumes:
  postgres_data:

networks:
  swarm_net:
    driver: overlay
    attachable: true

