services:
  web:
    image: lluuiizzz/dicapi-backend:latest
    networks:
      - swarm_net
    environment:
      - MEMCACHED_URL=cache:11211
      - DB_HOST=db
  db:
    image: postgres:15-alpine
    networks:
      - swarm_net
  cache:
    image: memcached:alpine
    networks:
      - swarm_net

networks:
  swarm_net: {}

